backend:
  # backend to use
  name: github
  # your github repo ex: benmarte/hugo-catalog
  repo: github-user-name/repo
  # optional, defaults to master
  branch: main
  # your netlify site name ex: netlify-site-name.netlify.app
  site_domain: "{{ secrets.NETLIFY_SITE_NAME }}"

# directory where your images are stored
media_folder: /static/images
# the path the site will use to store your images
public_folder: /images

# enables decap editorial workflow
publish_mode: editorial_workflow

# URL to your company logo to be used in the login screen, logo max width is 300px. Logo can be a relative path or a CDN url.
logo_url: https://benmarte.github.io/hugo-catalog-site/images/hugo-catalog-logo.svg

# Collection of pages decap can access
collections:
  # name
  - name: "content"
    # label displayed in decap under collections
    label: "Pages"
    # directory with markdow files
    folder: "/content"
    create: true
    # the filename will be used to generate the url to the page
    slug: "{{slug}}"
    # fields accessible in decap when creating or editing a page
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
